### ISSUE TITLE
Нет кнопки плеера

### ISSUE THREAD

**Issue by TristisOris** [Malanavi/Watch-and-download-on-Shikimori#5]
много где нет, в основном старые тайтлы на которые нет видео. думал связано с этим, но.

https://shikimori.one/animes/56579-jinyi-shen-jiang
![image](https://github.com/Malanavi/Watch-and-download-on-Shikimori/assets/1270117/35a71fd9-2437-4595-90c2-f35366f81443)
при этом в кодик серии уже давно залиты.
![image](https://github.com/Malanavi/Watch-and-download-on-Shikimori/assets/1270117/e446ee15-2fcd-41bf-9aa6-48482fe53b31)

Кнопка выводится только в заполненном блоке студии?
но например здесь нет студии.
![image](https://github.com/Malanavi/Watch-and-download-on-Shikimori/assets/1270117/d8297602-6255-4372-9c4c-d38d1d951ede)

**Comment by Malanavi** [comment]
На странице тайтла обычно есть две колонки:
![image](https://github.com/Malanavi/Watch-and-download-on-Shikimori/assets/89045089/ce693350-7857-4cf0-8813-6f0e0865c8f2)
В названии классов в html они называются левая и правая соответственно. Собственно, кнопка выводится в конец правой колонки. В твоём примере правой колонки нет вовсе, потому кнопка не выводится.
Честно говоря, не думал, что эта колонка может отстутствовать. Спасибо, подумаю куда ее можно выводить в таком случае)

**Comment by TristisOris** [comment]
Вижу, понял. Что-бы не залазить в инфоблок, наверное остается пихать кнопку в описание и выравнивать вправо.
![image](https://github.com/Malanavi/Watch-and-download-on-Shikimori/assets/1270117/8e4d9335-15b5-4b7e-a34b-9b38e5f2b571)
![image](https://github.com/Malanavi/Watch-and-download-on-Shikimori/assets/1270117/cf02a653-6b3c-4eea-8461-19396b0008e2)

**Comment by Malanavi** [comment]
Как оказалось, правая колонка есть, но она пустая. Ранее искался последний элемент в правой колонке, теперь кнопка просто добавляется в колонку (так даже логичней).
![image](https://github.com/Malanavi/Watch-and-download-on-Shikimori/assets/89045089/0e1ece9a-d55b-4fa5-844b-53c02aa8a086)

Обновление выложил.

**Comment by TristisOris** [comment]
работает, спасибо.
